mybatis-plus:
  mapper-locations: classpath:mappers/**/*Mapper.xml
  type-aliases-package: com.taozi.foodapp.pojo
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1